my_robot:
    #publish all joint states
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    #position controllers
    joint_01l_position_controller:
        type: effort_controllers/JointPositionController
        joint: joint_01l
        pid: {p: 100.0, i: 0.01, d: 10.0}
